on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Conditional Publish

jobs:
  publish:
    name: Publish to crates.io if not already published
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - crate: nft_storage_api
          - crate: nft_storage_core
          # - crate: nft_storage_cli
          # - crate: nft_storage_daemon
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.crate }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Read version from Cargo.toml
        id: read-version
        run: |
          VERSION=$(cargo read-manifest --manifest-path ${{ matrix.crate }}/Cargo.toml | jq -r .version)
          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if crate version is published
        id: check-published
        run: |
          echo "searching for ${{ matrix.crate }}"
          cargo search ${{ matrix.crate }} --limit 1
          echo $?
          echo "searching for ${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\"
          cargo search ${{ matrix.crate }} --limit 1 | grep -q "${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\""
          echo $?

          echo "if ${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\"
          if cargo search ${{ matrix.crate }} --limit 1 | grep -q "${{ matrix.crate }} = \"${{ steps.read-version.outputs.version }}\""; then
            echo "published=yes"
            echo "published=yes" >> $GITHUB_OUTPUT
          else
            echo "published=no"
            echo "published=no" >> $GITHUB_OUTPUT
          fi

      - name: Publish crate if not published
        if: ${{ steps.check-published.outputs.published }} == 'no'
        run: |
          echo ${{ steps.read-version.outputs.version }}
          cd ${{ matrix.crate }}
          cargo publish --token $CRATES_TOKEN
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
