on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Conditional Publish

jobs:
  publish:
    name: Publish to crates.io if not already published
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - crate: nft_storage_api
          - crate: nft_storage_core
          # - crate: nft_storage_cli
          # - crate: nft_storage_daemon
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.crate }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish crate
        run: |
          set +e
          cd ${{ matrix.crate }}
          cargo publish --token $CRATES_TOKEN
          set -e
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
